# TODO: Better name and description
name: print_beautiful
description: print() function that helps to understand the structure of the object printed

authors:
  - VictorPuga <victorpugaruiz@live.com.mx>
homepage: https://github.com/VictorPuga/print_beautiful
repository: https://github.com/VictorPuga/print_beautiful

version: 0.0.1
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  ansicolor: ^1.0.2
  equatable: ^0.2.0
  meta: ^1.1.6